### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by nvx0** [ThatOneCalculator/DiscordRPCMaker-CLI#1]
C:\Users\nvx\Desktop\loaderConcept>discordrpcmaker-cli.exe
node:internal/fs/utils:343
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\Users\nvx\/AppData/Roaming/drpcm/\undefined.json'

**Comment by ThatOneCalculator** [comment]
Please actually READ THE INSTRUCTIONS ON THE REPO. It says how to use the program, you never gave it the ID to use.
